# Generated by Django 3.2.8 on 2021-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_commentaire_post_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='Post_related',
        ),
        migrations.AddField(
            model_name='post',
            name='commentaires',
            field=models.ManyToManyField(to='Post.Commentaire'),
        ),
    ]
