# Generated by Django 3.2.8 on 2021-10-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_demmande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demmande',
            name='client',
        ),
        migrations.CreateModel(
            name='Request_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.demmande')),
            ],
        ),
    ]
