# Generated by Django 3.2.8 on 2021-11-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ouvrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='demmande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
    ]
