# Generated by Django 3.2.8 on 2021-11-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_demmande_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demmande',
            old_name='client',
            new_name='cliente',
        ),
    ]
