# Generated by Django 3.2.8 on 2021-11-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_client_demmande_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demmande',
            name='cliente',
        ),
        migrations.AddField(
            model_name='demmande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demande', to='accounts.client'),
        ),
    ]
