# Generated by Django 3.2.8 on 2021-11-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211117_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouvrier',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='ouvrier',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.categorie'),
        ),
    ]
