# Generated by Django 3.2.8 on 2021-11-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211117_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrier',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.categorie'),
        ),
        migrations.AlterField(
            model_name='ouvrier',
            name='job',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
