# Generated by Django 3.2.8 on 2021-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_client_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='images/avatar-11.jpg', null=True, upload_to='images'),
        ),
    ]
