# Generated by Django 3.2.8 on 2021-12-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fromcl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='report',
            name='tocl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ouvrier'),
        ),
    ]
