# Generated by Django 3.2.8 on 2021-10-31 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateField(auto_now=True, null=True)),
                ('desciption', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_send',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='desciption',
        ),
        migrations.AddField(
            model_name='ticket',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.content_ticket'),
        ),
    ]
