# Generated by Django 3.2.8 on 2021-10-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_auto_20211031_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='content',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_send',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='desciption',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
