# Generated by Django 3.2.8 on 2021-10-31 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_auto_20211031_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_send',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='desciption',
        ),
        migrations.AddField(
            model_name='ticket',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.content_ticket'),
        ),
    ]
