# Generated by Django 3.2.8 on 2021-11-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_auto_20211031_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
